---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/yjqpro/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .osx
  - .p10k.zsh
  - .tmux.conf

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - bison
  - ccls
  - cmake
  - cowsay
  - doxygen
  - efm-langserver
  - gdb
  - gifsicle
  - git
  - pkg-config
  - gnupg
  - go
  - httpie
  - iperf
  - lua
  - luajit
  - luarocks
  - mas
  - mcrypt
  - neovim
  - nghttp2
  - ninja
  - nmap
  - node
  - nvm
  - openssl@3
  - php
  - pv
  - python@3.9
  - ripgrep
  - ssh-copy-id
  - tmux
  - wget
  - wrk
  - yamllint
  - zsh-history-substring-search

homebrew_taps:
  - github/gh
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - appcleaner
  - baidunetdisk
  - beyond-compare
  - chromedriver
  - dash
  - docker
  - dropbox
  - font-jetbrains-mono-nerd-font
  - go2shell
  - google-chrome
  - iina
  - karabiner-elements
  - keepassxc
  - kitty
  - licecap
  - macvim
  - oracle-jdk
  - pdf-expert
  - scatter
  - scroll-reverser
  - sequel-ace
  - slack
  - squirrel
  - telegram-desktop
  - the-unarchiver
  - virtualbox
  - yinxiangbiji
  - youdaodict

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
