---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/yjqpro/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .osx
  - .p10k.zsh
  - .tmux.conf

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - aom
  - apr
  - apr-util
  - argon2
  - aspell
  - autoconf
  - bash-completion
  - bdw-gc
  - bison
  - boost
  - brotli
  - c-ares
  - ca-certificates
  - cairo
  - cjson
  - clang-format
  - cmake
  - cmocka
  - cowsay
  - curl
  - dav1d
  - dbus
  - doxygen
  - efm-langserver
  - ffmpeg
  - ffmpeg@4
  - flac
  - fontconfig
  - freetds
  - freetype
  - frei0r
  - fribidi
  - gd
  - gettext
  - giflib
  - gifsicle
  - git
  - glib
  - gmp
  - gnupg
  - gnutls
  - go
  - gobject-introspection
  - graphite2
  - guile
  - harfbuzz
  - httpie
  - hugo
  - icu4c
  - imath
  - innoextract
  - iperf
  - jemalloc
  - jpeg
  - jpeg-xl
  - jq
  - krb5
  - kubernetes-cli
  - kustomize
  - lame
  - lazygit
  - leptonica
  - lf
  - libarchive
  - libass
  - libassuan
  - libavif
  - libb2
  - libbluray
  - libev
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libksba
  - libnghttp2
  - libogg
  - libpng
  - libpq
  - libpthread-stubs
  - librist
  - libsamplerate
  - libsndfile
  - libsodium
  - libsoxr
  - libssh2
  - libtasn1
  - libtermkey
  - libtiff
  - libtool
  - libunistring
  - libusb
  - libuv
  - libvidstab
  - libvmaf
  - libvorbis
  - libvpx
  - libx11
  - libxau
  - libxcb
  - libxdmcp
  - libxext
  - libxrender
  - libyaml
  - libzip
  - little-cms2
  - llvm
  - lua
  - lua-language-server
  - luajit
  - luajit-openresty
  - luarocks
  - luv
  - lz4
  - lzo
  - m4
  - mas
  - mbedtls
  - mcrypt
  - mhash
  - minikube
  - moreutils
  - mpdecimal
  - msgpack
  - ncurses
  - neovim
  - nettle
  - nghttp2
  - ninja
  - nmap
  - node
  - node@16
  - npth
  - oniguruma
  - opencore-amr
  - openexr
  - openjpeg
  - openldap
  - openssl@1.1
  - openssl@3
  - opus
  - p11-kit
  - p7zip
  - pcre
  - pcre2
  - php
  - pinentry
  - pipx
  - pixman
  - pkg-config
  - prettier
  - pv
  - python@3.10
  - python@3.9
  - rav1e
  - rbenv
  - readline
  - ripgrep
  - rtmpdump
  - rubberband
  - ruby-build
  - rust
  - scrcpy
  - sdl2
  - sevenzip
  - six
  - smartmontools
  - snappy
  - speex
  - sqlite
  - srt
  - ssh-copy-id
  - stylua
  - subversion
  - tcping
  - telnet
  - tesseract
  - theora
  - tidy-html5
  - tmux
  - tree-sitter
  - unbound
  - unibilium
  - unixodbc
  - unshield
  - utf8proc
  - webp
  - wget
  - wrk
  - x264
  - x265
  - xorgproto
  - xvid
  - xz
  - yamllint
  - you-get
  - zeromq
  - zimg
  - zsh-history-substring-search
  - zstd

homebrew_taps:
  - github/gh
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - android-platform-tools
  - appcleaner
  - baidunetdisk
  - beyond-compare
  - chromedriver
  - dash
  - dropbox
  - font-caskaydia-cove-nerd-font
  - font-jetbrains-mono-nerd-font
  - go2shell
  - google-chrome
  - iina
  - karabiner-elements
  - keepassxc
  - kitty
  - licecap
  - macvim
  - michaelvillar-timer
  - oracle-jdk
  - pdf-expert
  - scatter
  - scroll-reverser
  - sequel-ace
  - slack
  - squirrel
  - telegram-desktop
  - the-unarchiver
  - yinxiangbiji
  - youdaodict

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
