---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: yjqpro.dotfiles
    src: git+https://github.com/yjqpro/ansible-role-dotfiles.git
    version: 1.2.1

collections:
  - name: geerlingguy.mac
