---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Test .osx
  stat:
    path: "{{ osx_script }}"
  register: osx_st
- name: Debug osx stat
  debug:
    var: osx_st
    verbosity: 4
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
